#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!

* Contrapositive
** Definition
   It is when you take the hypothesis and conclusion of a conditional statement and switch and negate both.
   If the propostion is true the contrapositive will also be true.
** Example
   The statement "If you study you will get an A" will turn into "if you did not get an A then you did not study"

* Converse
** Definition
   It is when you switch the hypothesis and conclusion of a condition statement.
   The propostion may be true but the converse will be false.
** Example
   The statement "If you study you will get an A" will turn into "If you got an A then you studied"

* Inverse
** Definition
   It is when you negate both the hypothesis and the conclusion of a conditional statement.
   The propostion may be true but the inverse may be false.
** Example
   The statement "If you study you will get an A" becomes "If you do not study you will not get an A"

* R: real numbers
** Definition
   It is all numbers on the number line. It includes positives, negatives, integers, rational numbers, etc.
** Example
   1, 2, 3, 4, 5, 1/2, -6, -122, 3/112.

* Z: integers
** Definition
   All positive and negative whole numbers. 
** Example
   1, 2, 3, 4, -5, -55, -32, 0.

* Q: rational numbers
** Definition
   All positive and negative fractions.
** Example
   1/2, 3/4, 5/6, 111/25.

* Predicate
** Definition
   A predicate is either a relation or the boolean-valued function that amounts to the indicator function of the relation
** Example
   Function P:x->{true,false} is called a predicate on X. It is used to check whether the statement is true or false.

* Domain
** Definition
   It is the set of the independant variables defined in a function.
   Usually it is the X values used to obtain the Y values.
** Example
   In the function F(x)=x+2 it would be all acceptable values for x.

* CoDomain
** Definition
   It is the set in which all the outputs of a function will fall into.
   Also refered to as the range.
** Example
   It is all the outcomes of all possible inputs of the function F(x)=x^2+5

* Quantifier
** Definition
** Example 

* Antecedent
** Definition
** Example

* Consequent
** Definition
** Example

* Set
** Definition
** Example

* Fallacy
** Definition
** Example

* Biconditional
** Definition
** Example

* Sufficient condition
** Definition
** Example

* Necessary condition
** Definition
** Example

~p

 p ^ q

 p V q

 p XOR q

 p == q

 p -> q

 p <--> q

 Three dots in a triangle

 upside down A

 Backwards E

 union

 intersection

 Commutative laws

 associative laws

 distributive laws

 identity laws

 negation laws

 double negative law

 idempotent laws

 universal bound laws

 De morgan's laws

 absorption laws

 negations of t and c

 vacuously true

 Modus Ponens

 Modus Tollens

 Elimination: valid argument form

 Transitivity: Valid Argument form
